<template>
  <div class="bg-[#2c3259] h-screen relative pt-[60px] overflow-y-auto">
    <RouterLink to="/" class="absolute z-50 left-8 top-5 h-[42px] flex items-center justify-center">
      <img src="@/assets/images/mbake-logo.png" class="md:w-[140px] w-[110px]" />
    </RouterLink>
    <span class="absolute top-0 w-full h-[52%] [background:linear-gradient(269.26deg,#c24fb6_6.59%,#3f51b8_94.04%)] [clip-path:polygon(0_0,100%_0,100%_76%,0_100%)] z-20"></span>
    <span class="absolute top-[38%] w-full h-[52%] [background:radial-gradient(64.65%_109.1%_at_55%_-20.93%,#ff00e4_15.1%,#2c3259_100%)] z-10"></span>
    <div class="text-white font-[Rubik,sans-serif] relative z-30 px-[10px]">
      <div class="max-w-[900px] pt-[15px] lg:pt-[45px] mx-auto">
        <div class="text-center">
          <h1 class="lg:text-[2.5rem] [font-size:calc(1.375rem_+_1.5vw)] font-medium [letter-spacing:.06rem]">OPBNB t BMR FAUCET</h1>
          <div class="mt-6 text-xl font-medium">Fast and reliable. 100 tBMR/day.</div>
        </div>
        <div class="mt-[22px] pb-8">
          <!-- send box -->
          <div class="max-w-[900px] border border-white bg-[#fffff2] rounded-t-3xl pt-9 pb-4 px-9">
            <!-- address -->
            <div class="flex flex-col md:flex-row">
              <div class="w-full md:w-3/4 md:mr-2">
                <input ref="addressElement" autofocus v-model="address" :disabled="disabled" @keyup.enter="onSend" class="disabled:bg-[#e9ecef] bg-[#f9f9fb] w-full border border-[#caced4] m-0 p-0 rounded-lg text-black text-base h-[46px] appearance-none outline-none px-4 py-2 focus:bg-white focus:border-[#86b7fe] focus:text-[#212529] focus:[box-shadow:0_0_0_.25rem_#0d6efd40]" placeholder="Enter Your Wallet Address (0x...)" />
              </div>
              <div class="w-full mt-2 md:w-1/4 md:mt-0">
                <button @click="onSend" :disabled="disabled" class="disabled:bg-[#212529] disabled:border-[#212529] disabled:text-[#fff] disabled:opacity-60 disabled:pointer-events-none focus:outline-none w-full [background:linear-gradient(90deg,_#6E56FF_0%,_#F41FFF_100%)] font-bold text-center rounded-2xl cursor-pointer h-[46px] border-0 appearance-none flex items-center justify-center">
                  <span class="text-xl">
                    <template v-if="disabled">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="40" height="40" style="shape-rendering: auto; display: block;" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle cx="30" cy="50" fill="#e90c59" r="20">
                        <animate attributeName="cx" repeatCount="indefinite" dur="1s" keyTimes="0;0.5;1" values="30;70;30" begin="-0.5s"></animate>
                      </circle>
                      <circle cx="70" cy="50" fill="#46dff0" r="20">
                        <animate attributeName="cx" repeatCount="indefinite" dur="1s" keyTimes="0;0.5;1" values="30;70;30" begin="0s"></animate>
                      </circle>
                      <circle cx="30" cy="50" fill="#e90c59" r="20">
                        <animate attributeName="cx" repeatCount="indefinite" dur="1s" keyTimes="0;0.5;1" values="30;70;30" begin="-0.5s"></animate>
                        <animate attributeName="fill-opacity" values="0;0;1;1" calcMode="discrete" keyTimes="0;0.499;0.5;1" dur="1s" repeatCount="indefinite"></animate>
                      </circle><g></g></g><!-- [ldio] generated by https://loading.io --></svg>
                    </template>
                    <template v-else>
                      <span>Send Me tBMR</span>
                    </template>
                  </span>
                </button>
              </div>
            </div>
            <!-- tips -->
            <p class="mt-4 text-base text-black">✅ Each address can only claim 1 time! In total 100,000 tBMR/day. Rest: 
              <span class="mx-2">{{ !loading ? restToken : '???' }}</span>
              <span>
                tBMR today.
              </span>
            </p>
            <!-- captcha -->
            <!-- <div class="mt-4 text-black">
              <Checkbox v-model="response" />
            </div> -->
          </div>
          <!-- trasactions -->
          <div class="max-w-[900px] border border-white text-base font-medium bg-[#fffff2] border-t-[#d9d9d9] rounded-b-3xl px-9">
            <div class="mt-8 mb-9">
              <div class="[background:linear-gradient(269.26deg,#c24fb6_6.59%,#3f51b8_94.04%)] rounded-t-lg flex">
                <div class="p-[14px] pr-[7px] h-[52px] w-full md:w-5/6">Your Transactions</div>
                <div class="py-[14px] w-1/6 hidden md:block">Time</div>
              </div>
              <div class="text-[#52555b] font-medium">
                <!-- data list -->
                <template v-for="item in viewTransactions" :key="item.createAt">
                  <div class="bg-white border-[#caced4] border-t-0 border flex last:rounded-b-lg">
                    <div class="p-[14px] pr-[7px] h-[52px] flex w-full md:w-5/6 items-center space-x-1">
                      <!-- <svg width="21" height="21" viewBox="0 0 58 58" fill="none" class="mr-2"><circle cx="29" cy="29" r="28" stroke="#52555b" stroke-opacity="0.5" stroke-linecap="round" stroke-dasharray="5 5"></circle><path d="M18.889 28.924l10.498 6.066 10.493-6.066-10.493-17.035-10.498 17.035z" fill="#52555b"></path><path d="M18.889 30.87l10.498 14.463L39.889 30.87l-10.502 6.066-10.498-6.066z" fill="#52555b"></path></svg> -->
                      <img :src="opBNB" width="21" height="21" alt="" />
                      <template v-if="item.hash">
                        <a :href="getTransationUrl(item.hash)" rel="noopener noreferrer" target="_blank" class="hover:text-[#52555b] text-[#52555b] underline overflow-hidden text-ellipsis whitespace-nowrap">{{ item.hash }}</a>
                      </template>
                      <template v-else-if="!loading"><span>-</span></template>
                      <template v-else><Skeleton class="w-1/2 h-full" /></template>
                    </div>
                    <div class="py-[14px] w-1/6 hidden md:block overflow-hidden text-ellipsis whitespace-nowrap">
                      <template v-if="item.createAt">
                        <Countdown :date="item.createAt" />
                      </template>
                      <template v-else-if="!loading">-</template>
                      <template v-else><Skeleton class="w-1/2 h-full" /></template>
                    </div>
                  </div>
                </template>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
// import { Checkbox } from 'vue-recaptcha';
import { RouterLink } from 'vue-router';
import Countdown from '@/components/ui/Countdown.vue';
import { getFaucetBalance, getFaucetTransaction, claimFaucetToken } from '@/lib/api';
import { getTransationUrl } from '@/lib/config';
import { useToast } from '@/components/ui/toast/use-toast'
import { Skeleton } from '@/components/ui/skeleton'
import opBNB from '@/assets/images/opBNB.svg';

const { toast } = useToast();
const address = ref('');
const sending = ref(false);
const loading = ref(true);
const transactions = ref<{ hash: string; createAt: number; }[]>([]);
const disabled = computed(() => sending.value);
// const response = ref();
const viewTransactions = computed(() => transactions.value.length ? transactions.value : [{ hash: '', createAt: 0 }]);
const addressElement = ref<HTMLInputElement | null>(null);
const restToken = ref(0);

function alertMessage(message: string) {
  toast({
    description: message
  });
}

async function doRefresh() {
  loading.value = true;
  try {
    await Promise.all([
      address.value && getFaucetTransaction({ address: address.value }).then((data) => {
        if (data.traded) {
          transactions.value = [
            {
              hash: data.hash,
              createAt: new Date(data.time).getTime(),
            }
          ]
        } else {
          transactions.value = [];
        }
      }),
      getFaucetBalance().then((data) => {
        restToken.value = data;
      })
    ])
  } finally {
    loading.value = false;
    focusAddress();
  }
}

async function onSend() {
  if (sending.value) {
    return;
  }
  if (!address.value) {
    alertMessage('Please enter your wallet address.');
    focusAddress();
    return;
  }
  // if (!response.value) {
  //   alertMessage('Please complete our reCAPTCHA and validations to make this request.');
  //   return;
  // }

  sending.value = true;

  try {
    // await claimFaucetToken({ address: address.value, respToken: response.value });
    await claimFaucetToken({ address: address.value });
    alertMessage('Success! Please wait for the transaction to be confirmed.');
  } catch (error) {
    const reason = error.message || 'An error occurred. Please try again later.';
    alertMessage(reason);
  } finally {
    sending.value = false;
    await doRefresh();
  }
}

function focusAddress() {
  setTimeout(() => {
    addressElement.value?.focus();
    addressElement.value?.click();
  }, 0);
}

doRefresh();
</script>
